import { Lang } from '../../translations';

export interface CaseStudy {
    slug: string;
    num: number;
    icon: string;
    gradient: string;
    link?: string;
}

export const caseStudies: CaseStudy[] = [
    { slug: 'chatbot-ai-ecommerce', num: 1, icon: '🤖', gradient: 'linear-gradient(135deg, #e94560, #ff6b81)' },
    { slug: 'sklep-shopify-ai', num: 2, icon: '🛒', gradient: 'linear-gradient(135deg, #10b981, #34d399)' },
    { slug: 'automatyzacja-n8n', num: 3, icon: '⚡', gradient: 'linear-gradient(135deg, #f59e0b, #fbbf24)' },
    { slug: 'aplikacja-mvp', num: 4, icon: '📱', gradient: 'linear-gradient(135deg, #8b5cf6, #a78bfa)' },
    { slug: 'automatyzacja-nieruchomosci', num: 5, icon: '🏠', gradient: 'linear-gradient(135deg, #eab308, #f59e0b)' },
    { slug: 'kamar-serwis', num: 6, icon: '🏗️', gradient: 'linear-gradient(135deg, #f97316, #facc15)', link: 'https://kamar-serwis.web.app/' },
];

const csTranslations: Record<string, Record<string, string>> = {
    pl: {
        'cs.back': '← Wróć do strony głównej',
        'cs.challenge': 'Wyzwanie',
        'cs.solution': 'Rozwiązanie',
        'cs.results': 'Rezultaty',
        'cs.techs': 'Technologie',
        'cs.timeline': 'Czas realizacji',
        'cs.cta.title': 'Chcesz podobne wyniki?',
        'cs.cta.button': 'Umów Konsultację →',
        'cs.visitSite': 'Zobacz projekt online →',
        'cs.clientLabel': 'Klient',

        'chatbot-ai-ecommerce.title': 'Chatbot AI dla E-commerce',
        'chatbot-ai-ecommerce.subtitle': 'Inteligentny agent AI obsługujący klientów 24/7 i zwiększający konwersję o 40%',
        'chatbot-ai-ecommerce.client': 'Sklep e-commerce, branża fashion',
        'chatbot-ai-ecommerce.timeline': '4 tygodnie',
        'chatbot-ai-ecommerce.challenge': 'Klient borykał się z rosnącą liczbą zapytań od klientów, szczególnie poza godzinami pracy. Dział wsparcia był przeciążony — średni czas odpowiedzi wynosił 4 godziny, a 30% klientów rezygnowało z zakupu z powodu braku natychmiastowej pomocy. Potrzebne było rozwiązanie, które automatycznie obsłuży większość zapytań bez utraty jakości obsługi.',
        'chatbot-ai-ecommerce.solution': 'Wdrożyliśmy zaawansowanego agenta AI opartego na Google Gemini, zintegrowanego z bazą produktów i historią zamówień. Agent rozumie kontekst rozmowy, rekomenduje produkty na podstawie preferencji klienta i automatycznie eskaluje złożone sprawy do konsultantów. Dodaliśmy multi-kanałową obsługę (web chat, email, SMS) i dashboard z metrykami w czasie rzeczywistym.',
        'chatbot-ai-ecommerce.result1.value': '-65%',
        'chatbot-ai-ecommerce.result1.label': 'Ticketów wsparcia',
        'chatbot-ai-ecommerce.result2.value': '+40%',
        'chatbot-ai-ecommerce.result2.label': 'Wzrost konwersji',
        'chatbot-ai-ecommerce.result3.value': '24/7',
        'chatbot-ai-ecommerce.result3.label': 'Dostępność',
        'chatbot-ai-ecommerce.result4.value': '<30s',
        'chatbot-ai-ecommerce.result4.label': 'Czas odpowiedzi',
        'chatbot-ai-ecommerce.techs': 'Google Gemini,N8N,Firebase,REST API,React,WebSocket',

        'sklep-shopify-ai.title': 'Sklep Shopify z AI',
        'sklep-shopify-ai.subtitle': 'Profesjonalny sklep z rekomendacjami AI i automatycznym marketingiem',
        'sklep-shopify-ai.client': 'Startup, branża beauty & wellness',
        'sklep-shopify-ai.timeline': '5 tygodni',
        'sklep-shopify-ai.challenge': 'Klient przechodził z Allegro na własny sklep online. Wyzwanie: brak doświadczenia w e-commerce, niska rozpoznawalność marki i ograniczony budżet marketingowy. Potrzebny był sklep, który nie tylko dobrze wygląda, ale aktywnie sprzedaje dzięki personalizacji i automatyzacji.',
        'sklep-shopify-ai.solution': 'Zbudowaliśmy custom sklep na Shopify z systemem rekomendacji AI analizującym zachowania klientów. Wdrożyliśmy automatyzację email marketingu (porzucone koszyki, cross-sell, welcome series), zintegrowany Google Analytics z enhanced e-commerce tracking i zoptymalizowaną ścieżkę zakupową. Sklep osiąga 2.1s ładowania dzięki optymalizacji performance.',
        'sklep-shopify-ai.result1.value': '+120%',
        'sklep-shopify-ai.result1.label': 'Wzrost sprzedaży',
        'sklep-shopify-ai.result2.value': '2.1s',
        'sklep-shopify-ai.result2.label': 'Czas ładowania',
        'sklep-shopify-ai.result3.value': '+85%',
        'sklep-shopify-ai.result3.label': 'Ruch organiczny',
        'sklep-shopify-ai.result4.value': '35%',
        'sklep-shopify-ai.result4.label': 'Powtórne zakupy',
        'sklep-shopify-ai.techs': 'Shopify,Klaviyo,Google Analytics,Meta Pixel,AI Recommendations,Stripe',

        'automatyzacja-n8n.title': 'System Automatyzacji N8N',
        'automatyzacja-n8n.subtitle': 'Zautomatyzowane 15 procesów biznesowych oszczędzając 25 godzin tygodniowo',
        'automatyzacja-n8n.client': 'Firma produkcyjna, 50+ pracowników',
        'automatyzacja-n8n.timeline': '3 tygodnie',
        'automatyzacja-n8n.challenge': 'Firma traciła 25+ godzin tygodniowo na powtarzalne zadania: ręczne wprowadzanie danych, kopiowanie informacji między systemami, tworzenie raportów i wysyłanie powiadomień. Pracownicy wykonywali te same operacje codziennie, co prowadziło do błędów i frustracji.',
        'automatyzacja-n8n.solution': 'Przeprowadziliśmy audyt wszystkich procesów i zidentyfikowaliśmy 15 kandydatów do automatyzacji. Wdrożyliśmy N8N z integracjami: ERP ↔ CRM (synchronizacja danych), automatyczne fakturowanie po zamknięciu zamówienia, raporty dzienne dla zarządu, powiadomienia Slack na kluczowe eventy i monitoring stanów magazynowych z auto-zamówieniami.',
        'automatyzacja-n8n.result1.value': '25h',
        'automatyzacja-n8n.result1.label': 'Oszczędność/tydzień',
        'automatyzacja-n8n.result2.value': '15',
        'automatyzacja-n8n.result2.label': 'Procesów',
        'automatyzacja-n8n.result3.value': '-90%',
        'automatyzacja-n8n.result3.label': 'Błędów manualnych',
        'automatyzacja-n8n.result4.value': '3x',
        'automatyzacja-n8n.result4.label': 'Szybsze raporty',
        'automatyzacja-n8n.techs': 'N8N,REST API,Slack,Google Sheets,Webhooks,PostgreSQL',

        'aplikacja-mvp.title': 'Aplikacja MVP w 10 Tygodni',
        'aplikacja-mvp.subtitle': 'Od koncepcji do App Store z oceną 4.8★ w 10 tygodni',
        'aplikacja-mvp.client': 'Startup fitness tech',
        'aplikacja-mvp.timeline': '10 tygodni',
        'aplikacja-mvp.challenge': 'Założyciel startupu miał pomysł na aplikację fitness z elementami AI, ale ograniczony budżet i brak zespołu technicznego. Potrzebował MVP, który pozwoli zwalidować pomysł z prawdziwymi użytkownikami i pozyskać inwestora.',
        'aplikacja-mvp.solution': 'Przeprowadziliśmy warsztaty discovery, zdefiniowaliśmy core features i zbudowaliśmy MVP w React Native. Aplikacja łączy plany treningowe generowane przez AI z elementami gamifikacji. Zintegrowaliśmy HealthKit/Google Fit, push notifications i system achievements. Po 10 tygodniach app trafił do App Store i Google Play.',
        'aplikacja-mvp.result1.value': '10',
        'aplikacja-mvp.result1.label': 'Tygodni do launch',
        'aplikacja-mvp.result2.value': '4.8★',
        'aplikacja-mvp.result2.label': 'Ocena w App Store',
        'aplikacja-mvp.result3.value': '2k+',
        'aplikacja-mvp.result3.label': 'Pobrań w mies. 1',
        'aplikacja-mvp.result4.value': '€200k',
        'aplikacja-mvp.result4.label': 'Pozyskane fundusze',
        'aplikacja-mvp.techs': 'React Native,Firebase,Google Gemini,HealthKit,Node.js,Figma',

        'automatyzacja-nieruchomosci.title': 'Automatyzacja Leadów Nieruchomości',
        'automatyzacja-nieruchomosci.subtitle': 'Agent AI obsługujący klientów 24/7 i automatycznie umawiający spotkania w luksusowych apartamentach',
        'automatyzacja-nieruchomosci.client': 'Agencja Nieruchomości Premium, Warszawa',
        'automatyzacja-nieruchomosci.timeline': '3 tygodnie',
        'automatyzacja-nieruchomosci.challenge': 'Dział sprzedaży tracił czas na ręczne odpowiadanie na podstawowe pytania z portali (Otodom, Morizon) i kwalifikację leadów. Ponad 40% zapytań przychodziło wieczorami i w weekendy, co skutkowało długim czasem odpowiedzi i utratą potencjalnych klientów.',
        'automatyzacja-nieruchomosci.solution': 'Zaprojektowaliśmy i wdrożyliśmy inteligentnego Agenta AI zintegrowanego z CRM-em firmy i portalami ogłoszeniowymi. Agent natychmiast odpowiada na zapytania, odpowiada na techniczne pytania o standard wykończenia, lokalizację i warunki umowy, a następnie proponuje termin prezentacji, wpisując go bezpośrednio do kalendarza agenta.',
        'automatyzacja-nieruchomosci.result1.value': '+400%',
        'automatyzacja-nieruchomosci.result1.label': 'Wzrost prezentacji',
        'automatyzacja-nieruchomosci.result2.value': '24/7',
        'automatyzacja-nieruchomosci.result2.label': 'Obsługa zapytań',
        'automatyzacja-nieruchomosci.result3.value': '-80%',
        'automatyzacja-nieruchomosci.result3.label': 'Czasu agentów',
        'automatyzacja-nieruchomosci.result4.value': '<2 min',
        'automatyzacja-nieruchomosci.result4.label': 'Czas odpowiedzi',
        'automatyzacja-nieruchomosci.techs': 'Google Gemini,N8N,Calendly API,Pipedrive CRM,Facebook API',

        'kamar-serwis.title': 'Kamar Serwis - Wypożyczalnia Sprzętu Budowlanego',
        'kamar-serwis.subtitle': 'Wielojęzyczna strona internetowa z zaawansowanym kalkulatorem zapytania ofertowego i optymalizacją SEO',
        'kamar-serwis.client': 'Kamar Serwis Sp. z o.o.',
        'kamar-serwis.timeline': '3 tygodnie',
        'kamar-serwis.challenge': 'Tradycyjna branża wynajmu sprzętu budowlanego w Warszawie cechuje się niską cyfryzacją. Klienci musieli dzwonić lub pisać maile, aby poznać stawki za wynajem maszyn (agregatów, sprężarek, minikoparek), co obciążało dział obsługi i wydłużało proces wyceny. Klient potrzebował platformy, która zautomatyzuje wyceny i ułatwi szybkie przesyłanie specyfikacji zapotrzebowania.',
        'kamar-serwis.solution': 'Zbudowaliśmy zoptymalizowaną pod SEO (Core Web Vitals) platformę SPA z dynamicznym kalkulatorem zapotrzebowania. Klienci mogą wybrać typ i ilość maszyn, określić czas wynajmu w dniach i otrzymać natychmiastową wycenę szacunkową. Integracja z Firebase i webhookami automatycznie przesyła specyfikację zamówienia do CRM, co pozwala handlowcom na szybką finalizację umowy.',
        'kamar-serwis.result1.value': '+150%',
        'kamar-serwis.result1.label': 'Zapytań ofertowych',
        'kamar-serwis.result2.value': '-40%',
        'kamar-serwis.result2.label': 'Czasu rozmów tel.',
        'kamar-serwis.result3.value': '100%',
        'kamar-serwis.result3.label': 'Zgodności z SEO',
        'kamar-serwis.result4.value': '<2.0s',
        'kamar-serwis.result4.label': 'Czas ładowania',
        'kamar-serwis.techs': 'React,Tailwind CSS,Vite,Firebase,SEO Audit,Lead Automation',
    },
    en: {
        'cs.back': '← Back to homepage',
        'cs.challenge': 'Challenge',
        'cs.solution': 'Solution',
        'cs.results': 'Results',
        'cs.techs': 'Technologies',
        'cs.timeline': 'Timeline',
        'cs.cta.title': 'Want similar results?',
        'cs.cta.button': 'Book Consultation →',
        'cs.visitSite': 'Visit live site →',
        'cs.clientLabel': 'Client',

        'chatbot-ai-ecommerce.title': 'AI Chatbot for E-commerce',
        'chatbot-ai-ecommerce.subtitle': 'Intelligent AI agent serving customers 24/7 and boosting conversions by 40%',
        'chatbot-ai-ecommerce.client': 'E-commerce store, fashion industry',
        'chatbot-ai-ecommerce.timeline': '4 weeks',
        'chatbot-ai-ecommerce.challenge': 'The client faced a growing number of customer inquiries, especially outside business hours. The support team was overloaded with a 4-hour average response time, and 30% of customers abandoned purchases due to lack of instant help.',
        'chatbot-ai-ecommerce.solution': 'We deployed an advanced AI agent powered by Google Gemini, integrated with the product catalog and order history. Multi-channel support (web, email, SMS) with real-time analytics dashboard.',
        'chatbot-ai-ecommerce.result1.value': '-65%', 'chatbot-ai-ecommerce.result1.label': 'Support tickets',
        'chatbot-ai-ecommerce.result2.value': '+40%', 'chatbot-ai-ecommerce.result2.label': 'Conversion increase',
        'chatbot-ai-ecommerce.result3.value': '24/7', 'chatbot-ai-ecommerce.result3.label': 'Availability',
        'chatbot-ai-ecommerce.result4.value': '<30s', 'chatbot-ai-ecommerce.result4.label': 'Response time',
        'chatbot-ai-ecommerce.techs': 'Google Gemini,N8N,Firebase,REST API,React,WebSocket',

        'sklep-shopify-ai.title': 'Shopify Store with AI',
        'sklep-shopify-ai.subtitle': 'Professional store with AI recommendations and automated marketing',
        'sklep-shopify-ai.client': 'Startup, beauty & wellness industry',
        'sklep-shopify-ai.timeline': '5 weeks',
        'sklep-shopify-ai.challenge': 'Client transitioning from marketplace to own online store with limited e-commerce experience and marketing budget.',
        'sklep-shopify-ai.solution': 'Built a custom Shopify store with AI recommendation engine, automated email marketing, and optimized checkout flow.',
        'sklep-shopify-ai.result1.value': '+120%', 'sklep-shopify-ai.result1.label': 'Sales increase',
        'sklep-shopify-ai.result2.value': '2.1s', 'sklep-shopify-ai.result2.label': 'Load time',
        'sklep-shopify-ai.result3.value': '+85%', 'sklep-shopify-ai.result3.label': 'Organic traffic',
        'sklep-shopify-ai.result4.value': '35%', 'sklep-shopify-ai.result4.label': 'Repeat purchases',
        'sklep-shopify-ai.techs': 'Shopify,Klaviyo,Google Analytics,Meta Pixel,AI Recommendations,Stripe',

        'automatyzacja-n8n.title': 'N8N Automation System',
        'automatyzacja-n8n.subtitle': '15 business processes automated, saving 25 hours weekly',
        'automatyzacja-n8n.client': 'Manufacturing company, 50+ employees',
        'automatyzacja-n8n.timeline': '3 weeks',
        'automatyzacja-n8n.challenge': 'Company was losing 25+ hours weekly on repetitive tasks: manual data entry, copying between systems, report creation.',
        'automatyzacja-n8n.solution': 'Audited all processes, identified 15 automation candidates, implemented N8N with ERP/CRM integrations, auto-invoicing, daily reports, Slack alerts.',
        'automatyzacja-n8n.result1.value': '25h', 'automatyzacja-n8n.result1.label': 'Saved/week',
        'automatyzacja-n8n.result2.value': '15', 'automatyzacja-n8n.result2.label': 'Processes',
        'automatyzacja-n8n.result3.value': '-90%', 'automatyzacja-n8n.result3.label': 'Manual errors',
        'automatyzacja-n8n.result4.value': '3x', 'automatyzacja-n8n.result4.label': 'Faster reports',
        'automatyzacja-n8n.techs': 'N8N,REST API,Slack,Google Sheets,Webhooks,PostgreSQL',

        'aplikacja-mvp.title': 'MVP App in 10 Weeks',
        'aplikacja-mvp.subtitle': 'From concept to App Store with 4.8★ rating in 10 weeks',
        'aplikacja-mvp.client': 'Fitness tech startup',
        'aplikacja-mvp.timeline': '10 weeks',
        'aplikacja-mvp.challenge': 'Startup founder had a fitness app idea with AI elements but limited budget and no tech team.',
        'aplikacja-mvp.solution': 'Discovery workshops, core feature definition, React Native MVP with AI workout plans and gamification, published to both app stores.',
        'aplikacja-mvp.result1.value': '10', 'aplikacja-mvp.result1.label': 'Weeks to launch',
        'aplikacja-mvp.result2.value': '4.8★', 'aplikacja-mvp.result2.label': 'App Store rating',
        'aplikacja-mvp.result3.value': '2k+', 'aplikacja-mvp.result3.label': 'Downloads month 1',
        'aplikacja-mvp.result4.value': '€200k', 'aplikacja-mvp.result4.label': 'Funding raised',
        'aplikacja-mvp.techs': 'React Native,Firebase,Google Gemini,HealthKit,Node.js,Figma',

        'automatyzacja-nieruchomosci.title': 'Real Estate Lead Automation',
        'automatyzacja-nieruchomosci.subtitle': 'AI Agent handling 24/7 inquiries and automatically scheduling luxury apartment viewings',
        'automatyzacja-nieruchomosci.client': 'Premium Real Estate Agency, Warsaw',
        'automatyzacja-nieruchomosci.timeline': '3 weeks',
        'automatyzacja-nieruchomosci.challenge': 'Sales team wasted too much time on basic qualification and manual portal replies. 40% of leads arrived during off-hours, leading to slow response times and loss of high-value prospects.',
        'automatyzacja-nieruchomosci.solution': 'Implemented an AI Agent integrated with CRM and portals. Instant replies, technical knowledge about standards/location, and automated scheduling directly into agents calendars.',
        'automatyzacja-nieruchomosci.result1.value': '+400%', 'automatyzacja-nieruchomosci.result1.label': 'Increase in viewings',
        'automatyzacja-nieruchomosci.result2.value': '24/7', 'automatyzacja-nieruchomosci.result2.label': 'Lead coverage',
        'automatyzacja-nieruchomosci.result3.value': '-80%', 'automatyzacja-nieruchomosci.result3.label': 'Agent time saved',
        'automatyzacja-nieruchomosci.result4.value': '<2 min', 'automatyzacja-nieruchomosci.result4.label': 'Response time',
        'automatyzacja-nieruchomosci.techs': 'Google Gemini,N8N,Calendly API,Pipedrive CRM,Facebook API',

        'kamar-serwis.title': 'Kamar Serwis - Construction Rental Platform',
        'kamar-serwis.subtitle': 'A multilingual website featuring an interactive rental cost estimator and SEO optimization',
        'kamar-serwis.client': 'Kamar Serwis Sp. z o.o.',
        'kamar-serwis.timeline': '3 weeks',
        'kamar-serwis.challenge': 'The traditional construction equipment rental market in Warsaw suffers from low digitalization. Customers had to make phone calls or send emails to get rental rates, increasing office workload and delaying quotes. The client needed a platform that automates pricing estimations and streamlines lead generation.',
        'kamar-serwis.solution': 'We built an SEO-optimized (Core Web Vitals) SPA platform with an interactive rental calculator. Customers can select equipment types, quantities, and rental duration to get an instant cost estimate. Firebase integration automatically posts the detailed lead payloads directly into the client\'s CRM.',
        'kamar-serwis.result1.value': '+150%',
        'kamar-serwis.result1.label': 'Online inquiries',
        'kamar-serwis.result2.value': '-40%',
        'kamar-serwis.result2.label': 'Call time saved',
        'kamar-serwis.result3.value': '100%',
        'kamar-serwis.result3.label': 'SEO optimization',
        'kamar-serwis.result4.value': '<2.0s',
        'kamar-serwis.result4.label': 'Page load time',
        'kamar-serwis.techs': 'React,Tailwind CSS,Vite,Firebase,SEO Audit,Lead Automation',
    },
    de: {
        'cs.back': '← Zurück zur Startseite',
        'cs.challenge': 'Herausforderung',
        'cs.solution': 'Lösung',
        'cs.results': 'Ergebnisse',
        'cs.techs': 'Technologien',
        'cs.timeline': 'Zeitrahmen',
        'cs.cta.title': 'Möchten Sie ähnliche Ergebnisse?',
        'cs.cta.button': 'Beratung buchen →',
        'cs.visitSite': 'Website besuchen →',
        'cs.clientLabel': 'Kunde',

        'chatbot-ai-ecommerce.title': 'KI-Chatbot für E-Commerce',
        'chatbot-ai-ecommerce.subtitle': 'Intelligenter KI-Agent für 24/7-Kundenservice mit 40% Konversionssteigerung',
        'chatbot-ai-ecommerce.client': 'E-Commerce-Shop, Mode',
        'chatbot-ai-ecommerce.timeline': '4 Wochen',
        'chatbot-ai-ecommerce.challenge': 'Wachsende Kundenanfragen außerhalb der Geschäftszeiten, überlastetes Support-Team.',
        'chatbot-ai-ecommerce.solution': 'KI-Agent mit Google Gemini, Produktkatalog-Integration und Multi-Kanal-Support.',
        'chatbot-ai-ecommerce.result1.value': '-65%', 'chatbot-ai-ecommerce.result1.label': 'Support-Tickets',
        'chatbot-ai-ecommerce.result2.value': '+40%', 'chatbot-ai-ecommerce.result2.label': 'Konversion',
        'chatbot-ai-ecommerce.result3.value': '24/7', 'chatbot-ai-ecommerce.result3.label': 'Verfügbarkeit',
        'chatbot-ai-ecommerce.result4.value': '<30s', 'chatbot-ai-ecommerce.result4.label': 'Antwortzeit',
        'chatbot-ai-ecommerce.techs': 'Google Gemini,N8N,Firebase,REST API,React,WebSocket',

        'sklep-shopify-ai.title': 'Shopify-Shop mit KI',
        'sklep-shopify-ai.subtitle': 'Professioneller Shop mit KI-Empfehlungen',
        'sklep-shopify-ai.client': 'Startup, Beauty & Wellness',
        'sklep-shopify-ai.timeline': '5 Wochen',
        'sklep-shopify-ai.challenge': 'Wechsel vom Marktplatz zum eigenen Online-Shop.',
        'sklep-shopify-ai.solution': 'Custom Shopify-Shop mit KI-Empfehlungssystem und automatisiertem Marketing.',
        'sklep-shopify-ai.result1.value': '+120%', 'sklep-shopify-ai.result1.label': 'Umsatzsteigerung',
        'sklep-shopify-ai.result2.value': '2.1s', 'sklep-shopify-ai.result2.label': 'Ladezeit',
        'sklep-shopify-ai.result3.value': '+85%', 'sklep-shopify-ai.result3.label': 'Organischer Traffic',
        'sklep-shopify-ai.result4.value': '35%', 'sklep-shopify-ai.result4.label': 'Wiederkäufe',
        'sklep-shopify-ai.techs': 'Shopify,Klaviyo,Google Analytics,Meta Pixel,AI Recommendations,Stripe',

        'automatyzacja-n8n.title': 'N8N Automatisierungssystem',
        'automatyzacja-n8n.subtitle': '15 Geschäftsprozesse automatisiert, 25 Stunden/Woche gespart',
        'automatyzacja-n8n.client': 'Produktionsunternehmen, 50+ Mitarbeiter',
        'automatyzacja-n8n.timeline': '3 Wochen',
        'automatyzacja-n8n.challenge': '25+ Stunden wöchentlich für repetitive Aufgaben verschwendet.',
        'automatyzacja-n8n.solution': 'N8N mit ERP/CRM-Integrationen, Auto-Rechnungsstellung, tägliche Berichte.',
        'automatyzacja-n8n.result1.value': '25h', 'automatyzacja-n8n.result1.label': 'Gespart/Woche',
        'automatyzacja-n8n.result2.value': '15', 'automatyzacja-n8n.result2.label': 'Prozesse',
        'automatyzacja-n8n.result3.value': '-90%', 'automatyzacja-n8n.result3.label': 'Manuelle Fehler',
        'automatyzacja-n8n.result4.value': '3x', 'automatyzacja-n8n.result4.label': 'Schnellere Berichte',
        'automatyzacja-n8n.techs': 'N8N,REST API,Slack,Google Sheets,Webhooks,PostgreSQL',

        'aplikacja-mvp.title': 'MVP-App in 10 Wochen',
        'aplikacja-mvp.subtitle': 'Vom Konzept zum App Store mit 4.8★ Bewertung',
        'aplikacja-mvp.client': 'Fitness-Tech-Startup',
        'aplikacja-mvp.timeline': '10 Wochen',
        'aplikacja-mvp.challenge': 'Startup-Gründer mit Fitness-App-Idee, begrenztem Budget und ohne Tech-Team.',
        'aplikacja-mvp.solution': 'Discovery-Workshops, React Native MVP mit KI-Trainingsplänen und Gamification.',
        'aplikacja-mvp.result1.value': '10', 'aplikacja-mvp.result1.label': 'Wochen bis Launch',
        'aplikacja-mvp.result2.value': '4.8★', 'aplikacja-mvp.result2.label': 'App Store Bewertung',
        'aplikacja-mvp.result3.value': '2k+', 'aplikacja-mvp.result3.label': 'Downloads Monat 1',
        'aplikacja-mvp.result4.value': '€200k', 'aplikacja-mvp.result4.label': 'Finanzierung',
        'aplikacja-mvp.techs': 'React Native,Firebase,Google Gemini,HealthKit,Node.js,Figma',

        'automatyzacja-nieruchomosci.title': 'KI-Automatisierung für Immobilien',
        'automatyzacja-nieruchomosci.subtitle': 'Ein KI-Agent für 24/7-Kundenbetreuung und automatische Besichtigungstermine',
        'automatyzacja-nieruchomosci.client': 'Premium-Immobilienagentur, Warschau',
        'automatyzacja-nieruchomosci.timeline': '3 Wochen',
        'automatyzacja-nieruchomosci.challenge': 'Das Vertriebsteam verlor Zeit mit manuellen Antworten auf Portalanfragen und Lead-Qualifizierung. Über 40% der Anfragen kamen abends und am Wochenende, was zu Verzögerungen führte.',
        'automatyzacja-nieruchomosci.solution': 'Implementierung eines KI-Agenten, integriert in CRM und Portale. Sofortige Antworten, technisches Wissen zu Standards/Lage und automatische Terminbuchung im Kalender der Makler.',
        'automatyzacja-nieruchomosci.result1.value': '+400%', 'automatyzacja-nieruchomosci.result1.label': 'Mehr Besichtigungen',
        'automatyzacja-nieruchomosci.result2.value': '24/7', 'automatyzacja-nieruchomosci.result2.label': 'Lead-Abdeckung',
        'automatyzacja-nieruchomosci.result3.value': '-80%', 'automatyzacja-nieruchomosci.result3.label': 'Zeitersparnis Makler',
        'automatyzacja-nieruchomosci.result4.value': '<2 Min', 'automatyzacja-nieruchomosci.result4.label': 'Antwortzeit',
        'automatyzacja-nieruchomosci.techs': 'Google Gemini,N8N,Calendly API,Pipedrive CRM,Facebook API',

        'kamar-serwis.title': 'Kamar Serwis - Baugeräte-Vermietungsplattform',
        'kamar-serwis.subtitle': 'Mehrsprachige Website mit interaktivem Mietpreiskalkulator und SEO-Optimierung',
        'kamar-serwis.client': 'Kamar Serwis Sp. z o.o.',
        'kamar-serwis.timeline': '3 Wochen',
        'kamar-serwis.challenge': 'Der traditionelle Mietmarkt für Baugeräte in Warschau leidet unter geringer Digitalisierung. Kunden mussten anrufen oder E-Mails schreiben, um Preise zu erfahren. Der Kunde brauchte eine Plattform zur Preisautomatisierung.',
        'kamar-serwis.solution': 'Wir bauten eine SEO-optimierte SPA mit interaktivem Mietkalkulator. Kunden wählen Geräte und Dauer für ein sofortiges Angebot. Firebase-Integration leitet Leads direkt an das CRM weiter.',
        'kamar-serwis.result1.value': '+150%', 'kamar-serwis.result1.label': 'Online-Anfragen',
        'kamar-serwis.result2.value': '-40%', 'kamar-serwis.result2.label': 'Telefonzeit gespart',
        'kamar-serwis.result3.value': '100%', 'kamar-serwis.result3.label': 'SEO-Optimierung',
        'kamar-serwis.result4.value': '<2.0s', 'kamar-serwis.result4.label': 'Ladezeit',
        'kamar-serwis.techs': 'React,Tailwind CSS,Vite,Firebase,SEO Audit,Lead Automation',
    },
};

export function ct(lang: Lang, key: string): string {
    return csTranslations[lang]?.[key] || csTranslations.pl[key] || key;
}
